# Generated by Django 5.1.3 on 2024-12-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_galeria_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
