# Generated by Django 5.1.3 on 2024-12-01 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_galeria_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='fotografia_data',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
